### PR TITLE
Make it compile with recent pico-sdk.

### PR DESCRIPTION
**Pull request by mgw93**
I needed to make some changes to get this running with a recent pico-sdk that includes lwip directly.

### CODE REVIEW

**Comment by liamfraser** [comment]
Looks good, although typically the PICO_SDK_PATH should not be defined in CMake and come from the PICO_SDK_PATH environment variable

**Comment by mgw93** [comment]
Yes. That is true. I only changed the existing path to make it work for me. But it’s probably better not to define it in CMake at all.

**Comment by Juddling** [comment]
Thanks @mgw93 !

**Comment by mgw93** [comment]
In retrospect, I pushed a few changes to this branch that I hadn’t originally intended to be part of the pull request. Such as making the main file a C++ file. In case that’s not wanted, it should be easy to revert though.

**Pull request merged**
